SET AUTOCOMMIT 1;
CREATE SEQUENCE AFOROCC_SEQUENCE;
--------------------------------------------------------------------------------
--Crear tablas
--------------------------------------------------------------------------------

CREATE TABLE ESPACIO
(   ID NUMBER,
    NOMBRE VARCHAR2(40 CHAR) NOT NULL,
    CENTRO_COMERCIAL NUMBER NOT NULL,
    LECTOR NUMBER NOT NULL,
    TIPO VARCHAR2(20 CHAR) NOT NULL,
    ESTADO NUMBER NOT NULL
);

CREATE TABLE LOCAL_COMERCIAL
(   ID_ESPACIO NUMBER NOT NULL,
    AREA NUMBER NOT NULL, 
    CLIENTES_ATENDIDOS NUMBER NOT NULL,
    TIPO_ESTABLECIMIENTO VARCHAR2(20 CHAR) NOT NULL,
    ESTADO VARCHAR2(10 CHAR) NOT NULL
);

CREATE TABLE PARQUEADERO
(   ID_ESPACIO NUMBER NOT NULL,
    CAPACIDAD_NORMAL NUMBER NOT NULL
);

CREATE TABLE BANIO
(   ID_ESPACIO NUMBER NOT NULL,
    NUMERO_SANITARIOS NUMBER NOT NULL
);

CREATE TABLE CENTRO_COMERCIAL
(   ID NUMBER,
    LECTOR_ENTRADA_CC NUMBER NOT NULL,
    AREA_TOTAL NUMBER NOT NULL
);

CREATE TABLE VISITA
(   ID NUMBER,
    HORA_INICIAL DATE NOT NULL,
    HORA_FINAL DATE,
    VISITANTE NUMBER NOT NULL,
    LECTOR NUMBER NOT NULL
);

CREATE TABLE VISITANTE
(   ID NUMBER,
    NOMBRE VARCHAR2(40 CHAR) NOT NULL,
    CORREO VARCHAR2(80 CHAR) NOT NULL,
    TELEFONO VARCHAR2(10 CHAR) NOT NULL,
    NOMBRE_EMERGENCIA VARCHAR2(40 CHAR) NOT NULL,
    TELEFONO_EMERGENCIA VARCHAR2(10 CHAR) NOT NULL,
    TIPO_VISITANTE VARCHAR2(40 CHAR) NOT NULL,
    CODIGO_QR VARCHAR2(200 CHAR) NOT NULL,
    CENTRO_COMERCIAL NUMBER NOT NULL,
    ESTADO NUMBER NOT NULL
);

CREATE TABLE TIPO_VISITANTE
(   NOMBRE VARCHAR2(40 CHAR),
    HORA_INICIAL_PERMITIDA DATE NOT NULL,
    HORA_FINAL_PERMITIDA DATE NOT NULL
);

CREATE TABLE LECTOR
(   ID NUMBER
);

CREATE TABLE ADMINISTRADOR
(   ID NUMBER,
    NOMBRE VARCHAR2(40 CHAR) NOT NULL
);

CREATE TABLE ADMIN_CC
(   ID_ADMIN NUMBER NOT NULL,
    CENTRO_COMERCIAL NUMBER NOT NULL
);

CREATE TABLE ADMIN_LOCAL
(   ID_ADMIN NUMBER NOT NULL,
    LOCAL_COMERCIAL NUMBER NOT NULL
);

CREATE TABLE TIPO_ESTABLECIMIENTO
(   NOMBRE VARCHAR2(20 CHAR),
    HORA_APERTURA DATE NOT NULL,
    HORA_CIERRE DATE NOT NULL
);

CREATE TABLE ESTADO_VISITANTE
(   ID NUMBER NOT NULL,
    NOMBRE VARCHAR2 (10 CHAR) NOT NULL,
    FECHA_ASIGNACION DATE NOT NULL
);

CREATE TABLE ESTADO_ESPACIO
(   ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(15 CHAR) NOT NULL,
    FECHA_ASIGNACION DATE NOT NULL
);




--------------------------------------------------------------------------------
--Agragar Primary Keys
--------------------------------------------------------------------------------

ALTER TABLE TIPO_ESTABLECIMIENTO
    ADD CONSTRAINT PK_TIPO_ESTABLECIMIENTO
    PRIMARY KEY (NOMBRE)
ENABLE;

ALTER TABLE ESPACIO
    ADD CONSTRAINT PK_ESPACIO
    PRIMARY KEY (ID)
ENABLE;

ALTER TABLE CENTRO_COMERCIAL
    ADD CONSTRAINT PK_CENTRO_COMERCIAL
    PRIMARY KEY (ID)
ENABLE;

ALTER TABLE VISITA
    ADD CONSTRAINT PK_VISITA
    PRIMARY KEY (ID)
ENABLE;

ALTER TABLE VISITANTE
    ADD CONSTRAINT PK_VISITANTE
    PRIMARY KEY (ID)
ENABLE;

ALTER TABLE TIPO_VISITANTE
    ADD CONSTRAINT PK_TIPO_VISITANTE
    PRIMARY KEY (NOMBRE)
ENABLE;

ALTER TABLE LECTOR
    ADD CONSTRAINT PK_LECTOR
    PRIMARY KEY (ID)
ENABLE;

ALTER TABLE ADMINISTRADOR
    ADD CONSTRAINT PK_ADMINISTRADOR
    PRIMARY KEY (ID)
ENABLE;

ALTER TABLE LOCAL_COMERCIAL
    ADD CONSTRAINT PK_LOCAL_COMERCIAL
    PRIMARY KEY (ID_ESPACIO)
ENABLE;

ALTER TABLE PARQUEADERO
    ADD CONSTRAINT PK_PARQUEADERO
    PRIMARY KEY (ID_ESPACIO)
ENABLE;

ALTER TABLE BANIO
    ADD CONSTRAINT PK_BANIO
    PRIMARY KEY (ID_ESPACIO)
ENABLE;

ALTER TABLE ADMIN_CC
    ADD CONSTRAINT PK_ADMIN_CC
    PRIMARY KEY (ID_ADMIN)
ENABLE;

ALTER TABLE ADMIN_LOCAL
    ADD CONSTRAINT PK_ADMIN_LOCAL
    PRIMARY KEY (ID_ADMIN)
ENABLE;

ALTER TABLE ESTADO_VISITANTE
    ADD CONSTRAINT PK_ESTADO_VISITANTE
    PRIMARY KEY (ID)
ENABLE;

ALTER TABLE ESTADO_ESPACIO
    ADD CONSTRAINT PK_ESTADO_ESPACIO
    PRIMARY KEY (ID)
ENABLE;


--------------------------------------------------------------------------------
--Agregar Foreign Keys y Checks
--------------------------------------------------------------------------------

--Tabla LOCAL_COMERCIAL
ALTER TABLE LOCAL_COMERCIAL
    ADD CONSTRAINT FK_ESPACIO_LOCAL
    FOREIGN KEY (ID_ESPACIO) REFERENCES ESPACIO (ID)
ENABLE;

ALTER TABLE LOCAL_COMERCIAL
    ADD CONSTRAINT FK_TIPO_ESTABLECIMIENTO_LOCAL
    FOREIGN KEY (TIPO_ESTABLECIMIENTO) REFERENCES TIPO_ESTABLECIMIENTO (NOMBRE)
ENABLE;

ALTER TABLE LOCAL_COMERCIAL
    ADD CONSTRAINT CK_AREA_LOC_COM_MAYOR_CERO CHECK (AREA > 0)
ENABLE;

ALTER TABLE LOCAL_COMERCIAL
    ADD CONSTRAINT CK_CLIENTES_LOC_COM_MAYOR_IGUAL_CERO CHECK (CLIENTES_ATENDIDOS >= 0)
ENABLE;

ALTER TABLE LOCAL_COMERCIAL
    ADD CONSTRAINT CK_ESTADO_ABIERTO_CERRADO CHECK (ESTADO IN ('ABIERTO', 'CERRADO'))
ENABLE;


--Tabla PARQUEADERO
ALTER TABLE PARQUEADERO
    ADD CONSTRAINT FK_ESPACIO_PARQUEADERO
    FOREIGN KEY (ID_ESPACIO) REFERENCES ESPACIO (ID)
ENABLE;

ALTER TABLE PARQUEADERO
    ADD CONSTRAINT CK_CAPACIDAD_PRQ_MAYOR_CERO CHECK (CAPACIDAD_NORMAL > 0)
ENABLE;


--Tabla BANIO
ALTER TABLE BANIO
    ADD CONSTRAINT FK_ESPACIO_BANIO
    FOREIGN KEY (ID_ESPACIO) REFERENCES ESPACIO (ID)
ENABLE;

ALTER TABLE BANIO
    ADD CONSTRAINT CK_N_SANITARIOS_BAN_MAYOR_CERO CHECK (NUMERO_SANITARIOS > 0)
ENABLE;


--Tabla ESPACIO
ALTER TABLE ESPACIO
    ADD CONSTRAINT FK_CENTRO_COMERCIAL_ESPACIO
    FOREIGN KEY (CENTRO_COMERCIAL) REFERENCES CENTRO_COMERCIAL (ID)
ENABLE;

ALTER TABLE ESPACIO
    ADD CONSTRAINT FK_ESTADO_ESPACIO
    FOREIGN KEY (ESTADO) REFERENCES ESTADO_ESPACIO (ID)
ENABLE;

ALTER TABLE ESPACIO
    ADD CONSTRAINT FK_LECTOR_ESPACIO
    FOREIGN KEY (LECTOR) REFERENCES LECTOR (ID)
ENABLE;

ALTER TABLE ESPACIO
    ADD CONSTRAINT ND_ID_LECTOR_ESPACIO
    UNIQUE (LECTOR)
ENABLE;
    
ALTER TABLE ESPACIO
    ADD CONSTRAINT CK_ID_ESP_MAYOR_CERO CHECK (ID > 0)
ENABLE;

ALTER TABLE ESPACIO
    ADD CONSTRAINT CK_TIPO_ESPACIO CHECK (TIPO IN ('LOCAL_COMERCIAL', 'BAÑO', 'PARQUEADERO', 'ASCENSOR'))
ENABLE;


--Tabla CENTRO_COMERCIAL
ALTER TABLE CENTRO_COMERCIAL
    ADD CONSTRAINT FK_LECTOR_CC
    FOREIGN KEY (LECTOR_ENTRADA_CC) REFERENCES LECTOR (ID)
ENABLE;

ALTER TABLE CENTRO_COMERCIAL
    ADD CONSTRAINT CK_ID_CC_MAYOR_CERO CHECK (ID > 0)
ENABLE;

ALTER TABLE CENTRO_COMERCIAL
    ADD CONSTRAINT CK_AREA_TOT_CC_MAYOR_CERO CHECK (AREA_TOTAL > 0)
ENABLE;

ALTER TABLE CENTRO_COMERCIAL
    ADD CONSTRAINT ND_ID_LECTOR_CC
    UNIQUE (LECTOR_ENTRADA_CC)
ENABLE;


--Tabla VISITA
ALTER TABLE VISITA
    ADD CONSTRAINT FK_VISITANTE_VISITA
    FOREIGN KEY (VISITANTE) REFERENCES VISITANTE (ID)
ENABLE;

ALTER TABLE VISITA
    ADD CONSTRAINT FK_LECTOR_VISITA
    FOREIGN KEY (LECTOR) REFERENCES LECTOR (ID)
ENABLE;

ALTER TABLE VISITA
    ADD CONSTRAINT CK_ID_VISITA_MAYOR_CERO CHECK (ID > 0)
ENABLE;


--Tabla VISITANTE
ALTER TABLE VISITANTE
    ADD CONSTRAINT FK_VISITANTE_TIPO_V
    FOREIGN KEY (TIPO_VISITANTE) REFERENCES TIPO_VISITANTE (NOMBRE)
ENABLE;

ALTER TABLE VISITANTE
    ADD CONSTRAINT FK_VISITANTE_CC
    FOREIGN KEY (CENTRO_COMERCIAL) REFERENCES CENTRO_COMERCIAL (ID)
ENABLE;

ALTER TABLE VISITANTE
    ADD CONSTRAINT FK_ESTADO_VISITANTE
    FOREIGN KEY (ESTADO) REFERENCES ESTADO_VISITANTE (ID)
ENABLE;

ALTER TABLE VISITANTE
    ADD CONSTRAINT CK_ID_VISITANTE_MAYOR_CERO CHECK (ID > 0)
ENABLE;

ALTER TABLE VISITANTE
    ADD CONSTRAINT CK_CORREO_VISITANTE CHECK (CORREO LIKE '%@%')
ENABLE;

ALTER TABLE VISITANTE
    ADD CONSTRAINT CK_TEL_VISITANTE CHECK (LENGTH(TELEFONO) = 10)
ENABLE;

ALTER TABLE VISITANTE
    ADD CONSTRAINT CK_TEL_EME_VISITANTE CHECK (LENGTH(TELEFONO_EMERGENCIA) = 10)
ENABLE;


--Tabla TIPO_VISITANTE
ALTER TABLE TIPO_VISITANTE
    ADD CONSTRAINT CK_TIPO_VIS_HORAS_CONSISTENTES CHECK (HORA_INICIAL_PERMITIDA < HORA_FINAL_PERMITIDA)
ENABLE;


--Tabla LECTOR
ALTER TABLE LECTOR
    ADD CONSTRAINT CK_ID_LECTOR_MAYOR_CERO CHECK (ID > 0)
ENABLE;


--Tabla ADMINISTRADOR
ALTER TABLE ADMINISTRADOR
    ADD CONSTRAINT CK_ID_ADMINISTRADOR_MAYOR_CERO CHECK (ID > 0)
ENABLE;


--Tabla ADMIN_CC
ALTER TABLE ADMIN_CC
    ADD CONSTRAINT FK_ADMIN_CC
    FOREIGN KEY (ID_ADMIN) REFERENCES ADMINISTRADOR (ID)
ENABLE;

ALTER TABLE ADMIN_CC
    ADD CONSTRAINT FK_ADMINISTRADOR_CC
    FOREIGN KEY (CENTRO_COMERCIAL) REFERENCES CENTRO_COMERCIAL (ID)
ENABLE;


--Tabla ADMIN_LOCAL
ALTER TABLE ADMIN_LOCAL
    ADD CONSTRAINT FK_ADMIN_LOCAL
    FOREIGN KEY (ID_ADMIN) REFERENCES ADMINISTRADOR (ID)
ENABLE;

ALTER TABLE ADMIN_LOCAL
    ADD CONSTRAINT FK_LOCAL_ADMINISTRADOR
    FOREIGN KEY (LOCAL_COMERCIAL) REFERENCES LOCAL_COMERCIAL (ID_ESPACIO)
ENABLE;


--Tabla TIPO_ESTABLECIMIENTO
ALTER TABLE TIPO_ESTABLECIMIENTO
    ADD CONSTRAINT CK_TIPO_EST_HORAS_CONSISTENTES CHECK (HORA_APERTURA < HORA_CIERRE)
ENABLE;


--Tabla ESTADO_VISITANTE
ALTER TABLE ESTADO_VISITANTE
    ADD CONSTRAINT CK_ESTADO_VISITANTE CHECK (NOMBRE IN ('POSITIVO', 'ROJO', 'NARANJA', 'VERDE'))
ENABLE;


--Tabla ESTADO_ESPACIO
ALTER TABLE ESTADO_ESPACIO
    ADD CONSTRAINT CK_ESTADO_ESPACIO CHECK (NOMBRE IN ('ROJO', 'NARANJA', 'VERDE', 'DESOCUPADO', 'DESHABILITADO'))
ENABLE;